<a href="https://colab.research.google.com/github/jishnujs1990/Study/blob/master/Mathematics_and_Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

#1. Load the dataset and handle any missing data by replacing null values with the mean
#value of the respective column. (Score 2)

import pandas as pd
import numpy as np

df = pd.read_csv('winequality-red.csv',sep=';')
#df

#missing data by mean
df.fillna(df.mean(), inplace=True)
#df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

Extract the following columns as vectors: alcohol,citric acid. (Score 2)

In [5]:
#alcohol - data frame
alcohol = df['alcohol']
alcohol

#citric acid - data frame
citric_acid = df['citric acid']
citric_acid

0       0.00
1       0.00
2       0.04
3       0.56
4       0.00
        ...
1594    0.08
1595    0.10
1596    0.13
1597    0.12
1598    0.47
Name: citric acid, Length: 1599, dtype: float64

In [13]:
#alcohol - Vector
alcohol = df['alcohol'].to_numpy()
print(alcohol)

[ 9.4  9.8  9.8 ... 11.  10.2 11. ]

In [14]:
#citric acid - Vector
citric_acid = df['citric acid'].to_numpy()
print(citric_acid)

[0.   0.   0.04 ... 0.13 0.12 0.47]

Select two features (e.g., alcohol and density) from the dataset and calculate the
covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the
selected columns.(Score 2)

In [10]:
X = df[['alcohol','density']].to_numpy()
#X

cv= np.cov(X.T)
cv

array([[ 1.13564740e+00, -9.97951790e-04],
       [-9.97951790e-04,  3.56202945e-06]])

Perform eigen decomposition on the covariance matrix you computed in question 3.
Identify and interpret the results:Identify the top 2 eigenvalues of the covariance
matrix,Identify the corresponding eigenvectors.(Score 2)

In [22]:
eigenvalues, eigenvectors = np.linalg.eig(cv)
print(eigenvalues)
print(eigenvectors)
# Sort them in descending order to easily find the top 2)
idx = eigenvalues.argsort()[::-1]
print(idx)
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]
print(f"Eigen Values:\n {eigenvalues}")
print(f"Eigen Vectors:\n {eigenvectors}")

[1.13564827e+00 2.68507580e-06]
[[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]
[0 1]
Eigen Values:
 [1.13564827e+00 2.68507580e-06]
Eigen Vectors:
 [[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]

In [23]:
#Which wine quality is most common in the dataset? How can you interpret the
#distribution of wine quality scores? (Score 2)

quality_counts = df['quality'].value_counts()
print(quality_counts)

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [24]:
most_common_count=quality_counts.idxmax()
print(most_common_count)

5